/*
 *  This JavaScript file for picture editor JavaScript component
 *  this component works for GnimJS
 *  Version 0.1.6
 *  Write by Ming
 *  Date 2012.04.16
 */
(function(f,l,K){function g(a){return a===l||a===K}function n(a){return'<div class="'+L+" "+s+a+'"></div>'}function t(a){var b=g(a.offsetX)?a.layerX:a.offsetX,a=g(a.offsetY)?a.layerY:a.offsetY;return{x:b,y:a}}function p(a){a.preventDefault&&a.preventDefault()}function u(a,b){function d(a){if(c._enable&&(p(a),!g(c._drag))){var a=t(a),b=c._selector;f(b+"."+m).css({left:(c._picl=c._picl+a.x-c._drag.x)+e,top:(c._pict=c._pict+a.y-c._drag.y)+e});c._drag=l;f(b+"."+q).removeClass(C);v.apply(c)}}function j(a){if(c._enable&&
a.currentTarget==a.target){p(a);var b=0;a.wheelDelta&&(b=a.wheelDelta/120);a.detail&&(b=-a.detail/3);0<b&&c.zoom(1/c.wheelzoom);0>b&&c.zoom(c.wheelzoom)}}var c=this,i;for(i in D)c[i]=D[i];c._selector=a;c._scale={};c._enable=!0;i=f(a);if(1!=i.length)throw Error("selector should find only one element");c.$dom=i;if(!g(b)){var h;if(!g(h=b.width))c._conw=h;if(!g(h=b.height))c._conh=h;if(!g(h=b.padding))for(var k in c._padding)c._padding[k]=h[k%h.length];if(!g(h=b.opacity))c._masko=h}i.empty().addClass(M);
f('<div class="'+N+'"><div class="'+w+'"></div></div>').appendTo(a);k=c._masko;f(n(x)).css({left:0,top:0,opacity:k}).appendTo(a);f(n(y)).css({right:0,top:0,opacity:k}).appendTo(a);f(n(z)).css({left:0,top:0,opacity:k}).appendTo(a);f(n(A)).css({left:0,bottom:0,opacity:k}).appendTo(a);f(n(E)).appendTo(a);f('<div class="'+q+'"></div>').appendTo(a).css({opacity:0.01}).mousedown(function(a){if(c._enable){p(a);var a=t(a),b=c._selector;c._drag=a;f(b+"."+q).addClass(C)}}).mousemove(function(a){c._enable&&
(p(a),g(c._drag)||(a=t(a),f(c._selector+"."+m).css({left:c._picl+a.x-c._drag.x+e,top:c._pict+a.y-c._drag.y+e})))}).mouseup(d).mouseout(d).bind("mousewheel",j).bind("DOMMouseScroll",j);c.setConSize()}function B(){for(var a in this._scale)F.apply(this,[a])}function v(a){for(var b in this._scale)G.apply(this,[b,a])}function F(a){O.apply(this,[a]);G.apply(this,[a])}function O(a){var a=this._scale[a],b=a.scale,d=this._conw-this._padding[1]-this._padding[3],g=this._conh-this._padding[0]-this._padding[2];
f(a.selector).css({width:d*b+e,height:g*b+e})}function G(a,b){var d=this._scale[a],g=d.selector,d=d.scale;b&&(f(g).empty(),f('<img src="'+this._picsrc+'" class="'+r+'" />').appendTo(g));f(g+"."+r).css({left:(this._picl-this._padding[3])*d+e,top:(this._pict-this._padding[0])*d+e,width:this._picw*d+e,height:this._pich*d+e})}var H=l,o=[50,50,50,50],M="editor-con",N="editor-con-inner",w="editor-con-picture",m="editor-picture",L="editor-mask",s="editor-mask-",x="left",y="right",z="top",A="bottom",E="center",
q="editor-drag-layer",C="editor-drag-layer-moving",r="editor-scale-picture",e="px",P=0,I={POSITION_LEFT_TOP:0,POSITION_LEFT_CENTER:1,POSITION_LEFT_BOTTOM:2,POSITION_CENTER_TOP:3,POSITION_CENTER_CENTER:4,POSITION_CENTER_BOTTOM:5,POSITION_RIGHT_TOP:6,POSITION_RIGHT_CENTER:7,POSITION_RIGHT_BOTTOM:8,DEFAULT_CON_WIDTH:300,DEFAULT_CON_HEIGHT:H,DEFAULT_MASK_OPACITY:0.5,DEFAULT_PADDING:o,DEFAULT_WHELL_ZOOM:0.8},D={wheelzoom:0.8,_picsrc:l,_picset:!1,_picloading:!1,_picautosize:!0,_conw:300,_conh:H,_picow:0,
_picoh:0,_picw:0,_pich:0,_picl:0,_pict:0,_padding:[o[0],o[1],o[2],o[3]],_masko:0.5,_drag:l,_scale:l,_selector:l};u.prototype={setPicture:function(a,b,d,j){var c=this,i=c._picset;c._picset=!0;c._picsrc=a;g(b)||g(d)?c._picautosize=!0:(c._picautosize=!1,c._picow=c._picw=parseInt(b),c._picoh=c._pich=parseInt(d));c._picloading=!0;f(c._selector+"."+w).empty();var h=f('<img src="'+a+'" class="'+m+'" />').load(function(b){b=f.IE?b.srcElement:this;if(c._picautosize){c._picow=c._picw=b.width;c._picoh=c._pich=
b.height;f(b).css({width:b.width+e,height:b.height+e})}f(b).css({left:(c._picl=parseInt((c._conw-c._picow)/2))+e,top:(c._pict=parseInt((c._conh-c._picoh)/2))+e,visibility:"visible"});c._picloading=false;var b=c._scale,d;for(d in b)f(b[d].selector+"."+r).attr("src",a);v.apply(c,[!i])}).appendTo(c._selector+"."+w).css({visibility:"hidden"});c._picautosize||h.css({width:b+e,height:d+e});g(j)||h.attr("pictureid",j);return c},resetPicture:function(){this._picset&&f(this._selector+"."+m).css({left:(this._picl=
parseInt((this._conw-this._picow)/2))+e,top:(this._pict=parseInt((this._conh-this._picoh)/2))+e,width:(this._picw=this._picow)+e,height:(this._pich=this._picoh)+e});B.apply(this);return this},setNeedSize:function(a,b){var d=this._padding;this.setConSize(a+d[1]+d[3],b+d[0]+d[2]);return this},setConSize:function(a,b){this._conw=a=g(a)?this._conw:a;this._conh=b=g(b)?this._conh:b;f(this._selector+","+this._selector+"."+q).css({width:a+e,height:b+e});this.setPadding();return this},setPadding:function(a){var b=
this._padding,d=this._selector+"."+s;if(!g(a))for(var j in b)b[j]=a[j%a.length];f(d+x).css({width:b[3]+e,height:this._conh+e});f(d+y).css({width:b[1]+e,height:this._conh+e});f(d+z).css({width:this._conw-b[1]-b[3]+e,height:b[0]+e,left:b[3]+e});f(d+A).css({width:this._conw-b[1]-b[3]+e,height:b[2]+e,left:b[3]+e});f(d+E).css({width:this._conw-b[1]-b[3]-2+e,height:this._conh-b[0]-b[2]-2+e,left:b[3]+e,top:b[0]+e});B.apply(this);return this},position:function(a,b,d){if(this._picset){var d=g(d)?0:d,j=parseInt(d/
3),c=this._padding[3],i=this._padding[0],h=this._conw-c-this._padding[1],k=this._conh-i-this._padding[2];switch(j){case 0:a+=c;break;case 1:a+=c-(this._picw-h)/2;break;case 2:a+=c-this._picw+h}switch(d%3){case 0:b+=i;break;case 1:b+=i-(this._pich-k)/2;break;case 2:b+=i-this._pich+k}f(this._selector+"."+m).css({left:(this._picl=parseInt(a))+e,top:(this._pict=parseInt(b))+e});B.apply(this)}},zoom:function(a){if(this._picset){var b=this._conw/2,d=this._conh/2,g=this._picw*a,a=this._pich*a,b=(this._picl-
b)*g/this._picw+b,d=(this._pict-d)*a/this._pich+d;f(this._selector+"."+m).css({width:(this._picw=parseInt(g))+e,height:(this._pich=parseInt(a))+e,left:(this._picl=parseInt(b))+e,top:(this._pict=parseInt(d))+e});v.apply(this)}},getEditInfo:function(){var a=this._selector;if(this._picset){var b={width:this._picw,height:this._pich,cut_width:this._conw-this._padding[1]-this._padding[3],cut_height:this._conh-this._padding[0]-this._padding[2],cut_left:this._padding[3]-this._picl,cut_top:this._padding[0]-
this._pict,original_width:this._picow,original_height:this._picoh,src:this._picsrc},a=f(a+"."+m).attr("pictureid");g(a)||(b.id=a);return b}return l},addScale:function(a,b,d){d=g(d)?P++:d;b={selector:a,scale:b};this.removeScale(d);this._scale[d]=b;f(a).empty().addClass("editor-scale");this._picset&&f('<img src="'+this._picsrc+'" class="'+r+'" />').appendTo(a);F.apply(this,[d])},removeScale:function(a){!g(a)&&!g(this._scale[a])&&(f(this._scale[a].selector).empty().removeClass("editor-scale"),this._scale[a]=
l,delete this._scale[a])},setEnable:function(a){this._enable=!!a;a?this.$dom.removeClass("editor-con-disable"):this.$dom.addClass("editor-con-disable");return this},setMaskOpacity:function(a){var b=[x,y,z,A];this._masko=a;for(var d in b)f(this._selector+"."+s+b[d]).css({opacity:a});return this}};for(var J in I)u[J]=I[J];window.PictureEditor=u})(Gnim,null);
